# Generated by Django 3.2 on 2021-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
