# Generated by Django 3.2 on 2021-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_reservation_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='preferred_food',
            field=models.CharField(blank=True, choices=[('indian', 'INDIAN'), ('chinese', 'INDIAN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved'), (None, 'Undefined')], default=None, max_length=10),
        ),
    ]
