# Generated by Django 3.2 on 2021-04-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='changed_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='preferred_food',
            field=models.CharField(blank=True, choices=[('indian', 'INDIAN'), ('chinese', 'CHINESE')], max_length=100),
        ),
    ]
