# Generated by Django 3.2 on 2021-05-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_auto_20210423_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(default='May 5', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_persons',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='occation',
            field=models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('casual', 'Casual')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='preferred_food',
            field=models.CharField(blank=True, choices=[('indian', 'INDIAN'), ('chinese', 'CHINESE'), ('italian', 'ITALIAN'), ('thai', 'THAi'), ('no_pref', 'NO PREFERENCE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('reserved', 'Reserved'), ('unreserved', 'Unreserved'), ('undefined', 'Undefined')], default='undefined', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
