# Generated by Django 3.2 on 2021-05-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_auto_20210505_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='preferred_food',
            field=models.CharField(blank=True, choices=[('indian', 'INDIAN'), ('chinese', 'CHINESE'), ('italian', 'ITALIAN'), ('thai', 'THAI'), ('no_pref', 'NO PREFERENCE')], max_length=100),
        ),
    ]
