# Generated by Django 3.2 on 2021-04-20 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'Starters'), ('2', 'Main Course'), ('3', 'Desserts'), ('4', 'Drinks'), ('5', 'Other')], default='5', max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='food_images/')),
                ('order_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('changed_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('changed_on', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.food')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_on', models.DateTimeField()),
                ('opened', models.BooleanField(default=False)),
                ('accept_status', models.BooleanField(blank=True)),
                ('status', models.CharField(choices=[('1', 'Placed'), ('2', 'Completed')], max_length=10)),
                ('payment_type', models.CharField(choices=[('1', 'Counter'), ('2', 'Online')], max_length=10)),
                ('completed_on', models.DateTimeField(blank=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('food', models.ManyToManyField(through='user.FoodOrder', to='user.Food')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resturant.reservation')),
                ('table', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resturant.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foodorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order'),
        ),
    ]
