# Generated by Django 3.2 on 2021-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_order_placed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('0', 'Undefined'), ('1', 'Counter'), ('2', 'Online')], default='0', max_length=10),
        ),
    ]
