# Generated by Django 3.2 on 2021-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210421_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='opened',
        ),
        migrations.AlterField(
            model_name='order',
            name='accept_status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Placed'), ('2', 'Completed')], default='1', max_length=10),
        ),
    ]
