# Generated by Django 3.2 on 2021-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210421_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
