# Generated by Django 3.2 on 2021-04-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
